const fs = require('fs');
const path = require('path');

const generatedComment =
  'Generated by tools/generate-binding.js. Do not edit.';
const supportedTypes = new Set([
  'void',
  'bool',
  'i8',
  'u8',
  'i16',
  'u16',
  'i32',
  'u32',
  'i64',
  'u64',
  'isize',
  'usize',
  'f32',
  'f64',
  'cstr',
]);
const statusTypes = new Set([
  'i8',
  'u8',
  'i16',
  'u16',
  'i32',
  'u32',
  'i64',
  'isize',
]);

function isObject(value) {
  return value && typeof value === 'object' && !Array.isArray(value);
}

function fail(message) {
  throw new Error(message);
}

function requireString(value, field) {
  if (typeof value !== 'string' || value.length === 0) {
    fail(`${field} must be a non-empty string`);
  }
}

function requireKeys(value, allowed, field) {
  for (const key of Object.keys(value)) {
    if (!allowed.has(key)) fail(`${field}.${key} is not supported`);
  }
}

function validateType(value, field, allowVoid) {
  requireString(value, field);
  if (!supportedTypes.has(value)) fail(`${field} has unsupported type '${value}'`);
  if (value === 'void' && !allowVoid) fail(`${field} cannot be void`);
}

function validateCIdentifier(value, field) {
  requireString(value, field);
  if (!/^[A-Za-z_][A-Za-z0-9_]*$/.test(value)) {
    fail(`${field} is not a C identifier`);
  }
}

function validateResourceName(value, field) {
  requireString(value, field);
  if (!/^[A-Za-z_][A-Za-z0-9_-]*$/.test(value)) {
    fail(`${field} is not a local resource name`);
  }
}

function validateCPointerType(value, field) {
  requireString(value, field);
  const pointerType =
    /^(?:(?:const|volatile)\s+)*(?:(?:struct|union)\s+)?[A-Za-z_][A-Za-z0-9_]*(?:\s*\*+)+$/;
  if (!pointerType.test(value)) {
    fail(`${field} must be a C pointer type`);
  }
}

function resourceMap(manifest) {
  return new Map((manifest.resources || []).map((resource, index) => [
    resource.name,
    {...resource, index},
  ]));
}

function requireResource(resources, name, field) {
  validateResourceName(name, field);
  if (!resources.has(name)) fail(`${field} references unknown resource '${name}'`);
}

function validateStatusCode(value, type, field) {
  if (!Number.isSafeInteger(value)) fail(`${field} must be a safe integer`);
  const ranges = {
    i8: [-128, 127],
    u8: [0, 255],
    i16: [-32768, 32767],
    u16: [0, 65535],
    i32: [-2147483648, 2147483647],
    u32: [0, 4294967295],
    isize: [-2147483648, 2147483647],
  };
  if (ranges[type] && (value < ranges[type][0] || value > ranges[type][1])) {
    fail(`${field} is outside ${type}'s range`);
  }
}

function validateReturn(value, field, resources) {
  if (typeof value === 'string') {
    validateType(value, field, true);
    return;
  }
  if (!isObject(value)) fail(`${field} must be a type string or object`);

  if (Object.prototype.hasOwnProperty.call(value, 'resource')) {
    requireKeys(value, new Set(['resource']), field);
    requireResource(resources, value.resource, `${field}.resource`);
    return;
  }

  requireKeys(value, new Set(['status', 'success']), field);
  validateType(value.status, `${field}.status`, false);
  if (!statusTypes.has(value.status)) {
    fail(`${field}.status must be a supported status integer type`);
  }
  if (!Array.isArray(value.success) || value.success.length === 0) {
    fail(`${field}.success must be a non-empty array`);
  }
  const codes = new Set();
  for (const [index, code] of value.success.entries()) {
    validateStatusCode(code, value.status, `${field}.success[${index}]`);
    if (codes.has(code)) fail(`${field}.success contains duplicate code ${code}`);
    codes.add(code);
  }
}

function validateArgument(value, field, resources) {
  if (typeof value === 'string') {
    validateType(value, field, false);
    return;
  }
  if (!isObject(value)) fail(`${field} must be a type string or object`);
  const hasResource = Object.prototype.hasOwnProperty.call(value, 'resource');
  const hasOutResource = Object.prototype.hasOwnProperty.call(value, 'outResource');
  if (hasResource === hasOutResource) {
    fail(`${field} must contain exactly one of resource or outResource`);
  }
  const key = hasResource ? 'resource' : 'outResource';
  requireKeys(value, new Set([key]), field);
  requireResource(resources, value[key], `${field}.${key}`);
}

function validateManifest(manifest) {
  if (!isObject(manifest)) {
    fail('manifest must be a JSON object');
  }
  requireKeys(
    manifest,
    new Set(['module', 'headers', 'resources', 'functions']),
    'manifest'
  );

  requireString(manifest.module, 'module');
  if (!/^[A-Za-z_][A-Za-z0-9_-]*(?:\.[A-Za-z_][A-Za-z0-9_-]*)*$/.test(manifest.module)) {
    fail(`invalid Toy module name '${manifest.module}'`);
  }

  if (!Array.isArray(manifest.headers) || manifest.headers.length === 0) {
    fail('headers must be a non-empty array');
  }
  const headers = new Set();
  for (const [index, header] of manifest.headers.entries()) {
    requireString(header, `headers[${index}]`);
    if (!/^[A-Za-z0-9_./+-]+$/.test(header) || header.includes('..')) {
      fail(`headers[${index}] is not a safe include path`);
    }
    if (headers.has(header)) fail(`duplicate header '${header}'`);
    headers.add(header);
  }

  if (manifest.resources !== undefined && !Array.isArray(manifest.resources)) {
    fail('resources must be an array');
  }
  const resourceNames = new Set();
  for (const [index, resource] of (manifest.resources || []).entries()) {
    const field = `resources[${index}]`;
    if (!isObject(resource)) fail(`${field} must be an object`);
    requireKeys(resource, new Set(['name', 'cType', 'destructor']), field);
    validateResourceName(resource.name, `${field}.name`);
    if (resourceNames.has(resource.name)) {
      fail(`duplicate resource '${resource.name}'`);
    }
    resourceNames.add(resource.name);
    validateCPointerType(resource.cType, `${field}.cType`);
    validateCIdentifier(resource.destructor, `${field}.destructor`);
  }
  const resources = resourceMap(manifest);

  if (!Array.isArray(manifest.functions) || manifest.functions.length === 0) {
    fail('functions must be a non-empty array');
  }
  const words = new Set();
  for (const [index, fn] of manifest.functions.entries()) {
    const field = `functions[${index}]`;
    if (!isObject(fn)) {
      fail(`${field} must be an object`);
    }
    requireKeys(fn, new Set(['name', 'word', 'returns', 'args']), field);
    validateCIdentifier(fn.name, `${field}.name`);
    if (fn.word !== undefined) requireString(fn.word, `${field}.word`);
    const word = fn.word || fn.name;
    if (!/^[A-Za-z_+*%<>=!?-][A-Za-z0-9_+*%<>=!?-]*$/.test(word)) {
      fail(`${field}.word is not a native Toy word name`);
    }
    if (words.has(word)) fail(`duplicate Toy word '${word}'`);
    words.add(word);

    validateReturn(fn.returns, `${field}.returns`, resources);
    if (!Array.isArray(fn.args)) fail(`${field}.args must be an array`);
    if (fn.args.length > 32) fail(`${field}.args supports at most 32 arguments`);
    let outputCount = 0;
    for (const [argIndex, argument] of fn.args.entries()) {
      validateArgument(argument, `${field}.args[${argIndex}]`, resources);
      if (isObject(argument) && argument.outResource !== undefined) {
        outputCount++;
      }
    }
    if (outputCount > 1) {
      fail(`${field}.args supports at most one output resource`);
    }
    if (outputCount > 0 &&
        !(fn.returns === 'void' ||
          (isObject(fn.returns) && fn.returns.status !== undefined))) {
      fail(`${field} output resources require void or status returns`);
    }
  }
  return manifest;
}

function loadManifest(manifestPath) {
  let manifest;
  try {
    manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));
  } catch (error) {
    fail(`could not read manifest '${manifestPath}': ${error.message}`);
  }
  return validateManifest(manifest);
}

function cString(value) {
  return JSON.stringify(value);
}

function cType(type, argument = false) {
  switch (type) {
    case 'void': return 'void';
    case 'bool': return 'bool';
    case 'i8': return 'int8_t';
    case 'u8': return 'uint8_t';
    case 'i16': return 'int16_t';
    case 'u16': return 'uint16_t';
    case 'i32': return 'int32_t';
    case 'u32': return 'uint32_t';
    case 'i64': return 'int64_t';
    case 'u64': return 'uint64_t';
    case 'isize': return 'intptr_t';
    case 'usize': return 'uintptr_t';
    case 'f32': return 'float';
    case 'f64': return 'double';
    case 'cstr': return argument ? 'char *' : 'const char *';
    default: fail(`internal error: unsupported type '${type}'`);
  }
}

function cDeclaration(type, name, argument = false) {
  const separator = type === 'cstr' ? '' : ' ';
  return `${cType(type, argument)}${separator}${name}`;
}

function isResourceInput(argument) {
  return isObject(argument) && argument.resource !== undefined;
}

function isOutputResource(argument) {
  return isObject(argument) && argument.outResource !== undefined;
}

function isResourceReturn(value) {
  return isObject(value) && value.resource !== undefined;
}

function isStatusReturn(value) {
  return isObject(value) && value.status !== undefined;
}

function getResource(manifest, name) {
  const resource = resourceMap(manifest).get(name);
  if (!resource) fail(`internal error: unknown resource '${name}'`);
  return resource;
}

function resourceTypeName(manifest, resource) {
  return `${manifest.module}.${resource.name}`;
}

function resourceDeclaration(resource, name) {
  return `${resource.cType} ${name}`;
}

function returnCType(manifest, value) {
  if (typeof value === 'string') return cType(value);
  if (isResourceReturn(value)) {
    return getResource(manifest, value.resource).cType;
  }
  return cType(value.status);
}

function argumentDescription(manifest, argument) {
  if (typeof argument === 'string') return argument;
  const resource = getResource(
    manifest,
    argument.resource !== undefined ? argument.resource : argument.outResource
  );
  return resourceTypeName(manifest, resource);
}

function argumentMessage(moduleName, word, index, type) {
  return cString(`${moduleName}.${word} argument ${index + 1} expected ${type}`);
}

function emitFailure(lines, condition, message) {
  lines.push(
    `    if (!(${condition})) {`,
    `        status = toy_fail(state, ${message});`,
    '        goto cleanup;',
    '    }'
  );
}

function emitArgumentDeclarations(lines, manifest, type, index) {
  const argument = `argument_${index}`;
  if (isResourceInput(type)) {
    const resource = getResource(manifest, type.resource);
    lines.push(
      `    void *raw_resource_${index} = NULL;`,
      `    ${resourceDeclaration(resource, argument)} = NULL;`
    );
    return;
  }
  if (isOutputResource(type)) {
    const resource = getResource(manifest, type.outResource);
    lines.push(`    ${resourceDeclaration(resource, argument)} = NULL;`);
    return;
  }
  switch (type) {
    case 'bool':
    case 'i64':
    case 'f32':
    case 'f64':
      lines.push(`    ${cDeclaration(type, argument)} = 0;`);
      break;
    case 'cstr':
      lines.push(
        `    ${cDeclaration(type, argument, true)} = NULL;`,
        `    const char *string_data_${index} = NULL;`,
        `    size_t string_length_${index} = 0;`
      );
      break;
    default:
      lines.push(
        `    int64_t raw_argument_${index} = 0;`,
        `    ${cDeclaration(type, argument)} = 0;`
      );
      break;
  }
}

function emitArgumentConversion(
  lines,
  manifest,
  word,
  type,
  index,
  visibleIndex,
  depth
) {
  const argument = `argument_${index}`;
  const raw = `raw_argument_${index}`;
  const message = argumentMessage(
    manifest.module,
    word,
    visibleIndex,
    argumentDescription(manifest, type)
  );
  if (isResourceInput(type)) {
    const resource = getResource(manifest, type.resource);
    emitFailure(
      lines,
      `toy_get_resource(state, ${depth}, ` +
        `${cString(resourceTypeName(manifest, resource))}, ` +
        `&raw_resource_${index})`,
      message
    );
    lines.push(`    ${argument} = raw_resource_${index};`);
    return;
  }
  switch (type) {
    case 'bool':
      emitFailure(lines, `toy_get_bool(state, ${depth}, &${argument})`, message);
      break;
    case 'i8':
      emitFailure(
        lines,
        `toy_get_int(state, ${depth}, &${raw}) && ${raw} >= INT8_MIN && ${raw} <= INT8_MAX`,
        message
      );
      lines.push(`    ${argument} = (int8_t)${raw};`);
      break;
    case 'u8':
      emitFailure(
        lines,
        `toy_get_int(state, ${depth}, &${raw}) && ${raw} >= 0 && ${raw} <= UINT8_MAX`,
        message
      );
      lines.push(`    ${argument} = (uint8_t)${raw};`);
      break;
    case 'i16':
      emitFailure(
        lines,
        `toy_get_int(state, ${depth}, &${raw}) && ${raw} >= INT16_MIN && ${raw} <= INT16_MAX`,
        message
      );
      lines.push(`    ${argument} = (int16_t)${raw};`);
      break;
    case 'u16':
      emitFailure(
        lines,
        `toy_get_int(state, ${depth}, &${raw}) && ${raw} >= 0 && ${raw} <= UINT16_MAX`,
        message
      );
      lines.push(`    ${argument} = (uint16_t)${raw};`);
      break;
    case 'i32':
      emitFailure(
        lines,
        `toy_get_int(state, ${depth}, &${raw}) && ${raw} >= INT32_MIN && ${raw} <= INT32_MAX`,
        message
      );
      lines.push(`    ${argument} = (int32_t)${raw};`);
      break;
    case 'u32':
      emitFailure(
        lines,
        `toy_get_int(state, ${depth}, &${raw}) && ${raw} >= 0 && (uint64_t)${raw} <= UINT32_MAX`,
        message
      );
      lines.push(`    ${argument} = (uint32_t)${raw};`);
      break;
    case 'i64':
      emitFailure(lines, `toy_get_int(state, ${depth}, &${argument})`, message);
      break;
    case 'u64':
      emitFailure(lines, `toy_get_int(state, ${depth}, &${raw}) && ${raw} >= 0`, message);
      lines.push(`    ${argument} = (uint64_t)${raw};`);
      break;
    case 'isize':
      emitFailure(
        lines,
        `toy_get_int(state, ${depth}, &${raw}) && ${raw} >= INTPTR_MIN && ${raw} <= INTPTR_MAX`,
        message
      );
      lines.push(`    ${argument} = (intptr_t)${raw};`);
      break;
    case 'usize':
      emitFailure(
        lines,
        `toy_get_int(state, ${depth}, &${raw}) && ${raw} >= 0 && (uint64_t)${raw} <= UINTPTR_MAX`,
        message
      );
      lines.push(`    ${argument} = (uintptr_t)${raw};`);
      break;
    case 'f32':
      emitFailure(
        lines,
        `binding_get_number(state, ${depth}, &raw_number_${index}) && ` +
          `(!isfinite(raw_number_${index}) || ` +
          `(raw_number_${index} >= -FLT_MAX && raw_number_${index} <= FLT_MAX))`,
        message
      );
      lines.push(`    ${argument} = (float)raw_number_${index};`);
      break;
    case 'f64':
      emitFailure(lines, `binding_get_number(state, ${depth}, &${argument})`, message);
      break;
    case 'cstr':
      emitFailure(
        lines,
        `toy_get_string(state, ${depth}, &string_data_${index}, &string_length_${index}) && ` +
          `(string_length_${index} == 0 || ` +
          `!memchr(string_data_${index}, '\\0', string_length_${index}))`,
        message
      );
      lines.push(
        `    ${argument} = malloc(string_length_${index} + 1);`,
        `    if (!${argument}) {`,
        `        status = toy_fail(state, ${cString(`${manifest.module}.${word} could not copy argument ${visibleIndex + 1}`)});`,
        '        goto cleanup;',
        '    }',
        `    memcpy(${argument}, string_data_${index}, string_length_${index});`,
        `    ${argument}[string_length_${index}] = '\\0';`
      );
      break;
    default:
      fail(`internal error: unsupported argument type '${type}'`);
  }
}

function emitScalarReturn(lines, moduleName, word, type) {
  const prefix = `${moduleName}.${word}`;
  switch (type) {
    case 'bool':
      lines.push('    status = toy_push_bool(state, result);');
      break;
    case 'i8':
    case 'u8':
    case 'i16':
    case 'u16':
    case 'i32':
    case 'u32':
    case 'i64':
    case 'isize':
      lines.push('    status = toy_push_int(state, (int64_t)result);');
      break;
    case 'u64':
    case 'usize':
      lines.push(
        '    if ((uint64_t)result > INT64_MAX) {',
        `        status = toy_fail(state, ${cString(`${prefix} returned ${type} outside Toy's range`)});`,
        '    } else {',
        '        status = toy_push_int(state, (int64_t)result);',
        '    }'
      );
      break;
    case 'f32':
    case 'f64':
      lines.push('    status = toy_push_float(state, (double)result);');
      break;
    case 'cstr':
      lines.push(
        '    if (!result) {',
        `        status = toy_fail(state, ${cString(`${prefix} returned a null cstr`)});`,
        '    } else if (!result_copy) {',
        `        status = toy_fail(state, ${cString(`${prefix} could not copy its cstr result`)});`,
        '    } else {',
        '        status = toy_push_string(state, result_copy, result_length);',
        '    }'
      );
      break;
    default:
      fail(`internal error: unsupported return type '${type}'`);
  }
}

function emitResourcePush(lines, manifest, resource, value, prefix) {
  lines.push(
    `    if (!${value}) {`,
    `        status = toy_fail(state, ${cString(`${prefix} returned a null ${resourceTypeName(manifest, resource)}`)});`,
    '    } else {',
    `        status = toy_push_resource(state, ` +
      `${cString(resourceTypeName(manifest, resource))}, ${value}, ` +
      `binding_destroy_resource_${resource.index}, NULL);`,
    `        if (status == TOY_OK) ${value} = NULL;`,
    '    }'
  );
}

function statusCondition(value) {
  return value.success
    .map((code) => `result == (${cType(value.status)})${code}`)
    .join(' || ');
}

function renderFunction(manifest, fn, index) {
  const word = fn.word || fn.name;
  const prefix = `${manifest.module}.${word}`;
  const visibleArgs = fn.args.filter((argument) => !isOutputResource(argument));
  const outputEntry = fn.args
    .map((argument, argIndex) => ({argument, argIndex}))
    .find((entry) => isOutputResource(entry.argument));
  const directResource = isResourceReturn(fn.returns)
    ? getResource(manifest, fn.returns.resource)
    : null;
  const lines = [
    `static toy_status binding_word_${index}(toy_state *state) {`,
    '    toy_status status = TOY_ERROR;',
  ];

  for (const [argIndex, type] of fn.args.entries()) {
    emitArgumentDeclarations(lines, manifest, type, argIndex);
    if (type === 'f32') lines.push(`    double raw_number_${argIndex} = 0.0;`);
  }
  if (fn.returns !== 'void') {
    lines.push(`    ${returnCType(manifest, fn.returns)} result = 0;`);
  }
  if (fn.returns === 'cstr') {
    lines.push(
      '    char *result_copy = NULL;',
      '    size_t result_length = 0;'
    );
  }
  if (fn.args.length > 0 || fn.returns !== 'void') lines.push('');

  let visibleIndex = 0;
  for (const [argIndex, type] of fn.args.entries()) {
    if (isOutputResource(type)) continue;
    emitArgumentConversion(
      lines,
      manifest,
      word,
      type,
      argIndex,
      visibleIndex,
      visibleArgs.length - visibleIndex - 1
    );
    visibleIndex++;
  }
  const callArguments = fn.args.map((argument, argIndex) =>
    isOutputResource(argument) ? `&argument_${argIndex}` : `argument_${argIndex}`
  );
  const call = `${fn.name}(${callArguments.join(', ')})`;
  if (fn.returns === 'void') lines.push(`    ${call};`);
  else lines.push(`    result = ${call};`);

  if (fn.returns === 'cstr') {
    lines.push(
      '    if (result) {',
      '        result_length = strlen(result);',
      '        result_copy = malloc(result_length + 1);',
      '        if (result_copy) {',
      '            memcpy(result_copy, result, result_length + 1);',
      '        }',
      '    }'
    );
  }

  if (visibleArgs.length > 0) {
    lines.push(
      '    if (!toy_pop(state, ' + visibleArgs.length + ')) {',
      `        status = toy_fail(state, ${cString(`${prefix} failed to pop its inputs`)});`,
      '        goto cleanup;',
      '    }'
    );
  }

  if (isStatusReturn(fn.returns)) {
    lines.push(
      `    if (!(${statusCondition(fn.returns)})) {`,
      `        status = binding_fail_status(state, ${cString(prefix)}, ` +
        '(long long)result);',
      '        goto cleanup;',
      '    }'
    );
  }

  if (directResource) {
    emitResourcePush(lines, manifest, directResource, 'result', prefix);
  } else if (outputEntry) {
    const resource = getResource(manifest, outputEntry.argument.outResource);
    emitResourcePush(
      lines,
      manifest,
      resource,
      `argument_${outputEntry.argIndex}`,
      prefix
    );
  } else if (typeof fn.returns === 'string' && fn.returns !== 'void') {
    emitScalarReturn(lines, manifest.module, word, fn.returns);
  } else {
    lines.push('    status = TOY_OK;');
  }
  lines.push('    goto cleanup;', '', 'cleanup:');
  for (const [argIndex, type] of fn.args.entries()) {
    if (type === 'cstr') lines.push(`    free(argument_${argIndex});`);
    if (isOutputResource(type)) {
      const resource = getResource(manifest, type.outResource);
      lines.push(
        `    if (argument_${argIndex}) {`,
        `        binding_destroy_resource_${resource.index}(` +
          `argument_${argIndex}, NULL);`,
        '    }'
      );
    }
  }
  if (fn.returns === 'cstr') lines.push('    free(result_copy);');
  if (directResource) {
    lines.push(
      '    if (result) {',
      `        binding_destroy_resource_${directResource.index}(result, NULL);`,
      '    }'
    );
  }
  lines.push('    return status;', '}', '');
  return lines;
}

function renderBinding(manifest) {
  const needsNumberHelper = manifest.functions.some((fn) =>
    fn.args.some((type) => type === 'f32' || type === 'f64')
  );
  const needsStatusHelper = manifest.functions.some((fn) =>
    isStatusReturn(fn.returns)
  );
  const lines = [
    `/* ${generatedComment} */`,
    '#include "toy_module.h"',
    '',
    ...manifest.headers.map((header) => `#include "${header}"`),
    '',
    '#include <float.h>',
    '#include <math.h>',
    '#include <stdint.h>',
    '#include <stdio.h>',
    '#include <stdlib.h>',
    '#include <string.h>',
    '',
  ];

  if (needsNumberHelper) {
    lines.push(
      'static bool binding_get_number(toy_state *state, size_t depth,',
      '                               double *value) {',
      '    if (toy_stack_type(state, depth) == TOY_TYPE_FLOAT) {',
      '        return toy_get_float(state, depth, value);',
      '    }',
      '    int64_t integer = 0;',
      '    if (!toy_get_int(state, depth, &integer)) return false;',
      '    *value = (double)integer;',
      '    return true;',
      '}',
      ''
    );
  }

  if (needsStatusHelper) {
    lines.push(
      'static toy_status binding_fail_status(toy_state *state,',
      '                                      const char *word,',
      '                                      long long value) {',
      '    char message[256];',
      '    snprintf(message, sizeof(message), "%s failed with status %lld",',
      '             word, value);',
      '    return toy_fail(state, message);',
      '}',
      ''
    );
  }

  for (const [index, resource] of (manifest.resources || []).entries()) {
    lines.push(
      `static void binding_destroy_resource_${index}(void *resource,`,
      '                                       void *userdata) {',
      '    (void)userdata;',
      `    ${resourceDeclaration(resource, 'value')} = resource;`,
      `    (void)${resource.destructor}(value);`,
      '}',
      ''
    );
  }

  for (const [index, fn] of manifest.functions.entries()) {
    lines.push(...renderFunction(manifest, fn, index));
  }

  lines.push('static const toy_native_word binding_words[] = {');
  for (const [index, fn] of manifest.functions.entries()) {
    lines.push(`    {${cString(fn.word || fn.name)}, binding_word_${index}},`);
  }
  lines.push(
    '};',
    '',
    'static const toy_module_export binding_module = {',
    '    sizeof(toy_module_export),',
    `    ${cString(manifest.module)},`,
    '    binding_words,',
    '    sizeof(binding_words) / sizeof(binding_words[0]),',
    '};',
    '',
    'TOY_MODULE_EXPORT const toy_module_export *toy_module_init(',
    '    uint32_t abi_version, const toy_module_api *api) {',
    '    if (!toy_module_bind(abi_version, api)) return NULL;',
    '    return &binding_module;',
    '}',
    ''
  );
  return lines.join('\n');
}

function main() {
  const args = process.argv.slice(2);
  const check = args[0] === '--check';
  const expectedLength = check ? 3 : 2;
  if (args.length !== expectedLength) {
    console.error(
      'usage: node tools/generate-binding.js [--check] <manifest.json> <output.c>'
    );
    process.exitCode = 2;
    return;
  }

  const manifestPath = path.resolve(args[check ? 1 : 0]);
  const outputPath = path.resolve(args[check ? 2 : 1]);
  const expected = renderBinding(loadManifest(manifestPath));
  if (check) {
    const actual = fs.existsSync(outputPath)
      ? fs.readFileSync(outputPath, 'utf8')
      : null;
    if (actual !== expected) {
      console.error(`out of date: ${outputPath}`);
      process.exitCode = 1;
    } else {
      console.log(`generated binding is up to date: ${outputPath}`);
    }
    return;
  }

  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  fs.writeFileSync(outputPath, expected);
  console.log(`wrote ${outputPath}`);
}

if (require.main === module) {
  try {
    main();
  } catch (error) {
    console.error(`error: ${error.message}`);
    process.exitCode = 1;
  }
}

module.exports = { renderBinding, validateManifest };
