const fs = require('fs');
const path = require('path');

const generatedComment =
  'Generated by tools/generate-binding.js. Do not edit.';
const supportedTypes = new Set([
  'void',
  'bool',
  'i8',
  'u8',
  'i16',
  'u16',
  'i32',
  'u32',
  'i64',
  'u64',
  'isize',
  'usize',
  'f32',
  'f64',
  'cstr',
]);

function fail(message) {
  throw new Error(message);
}

function requireString(value, field) {
  if (typeof value !== 'string' || value.length === 0) {
    fail(`${field} must be a non-empty string`);
  }
}

function requireKeys(value, allowed, field) {
  for (const key of Object.keys(value)) {
    if (!allowed.has(key)) fail(`${field}.${key} is not supported`);
  }
}

function validateType(value, field, allowVoid) {
  requireString(value, field);
  if (!supportedTypes.has(value)) fail(`${field} has unsupported type '${value}'`);
  if (value === 'void' && !allowVoid) fail(`${field} cannot be void`);
}

function validateManifest(manifest) {
  if (!manifest || typeof manifest !== 'object' || Array.isArray(manifest)) {
    fail('manifest must be a JSON object');
  }
  requireKeys(
    manifest,
    new Set(['schemaVersion', 'module', 'headers', 'functions']),
    'manifest'
  );
  if (manifest.schemaVersion !== 1) fail('schemaVersion must be 1');

  requireString(manifest.module, 'module');
  if (!/^[A-Za-z_][A-Za-z0-9_-]*(?:\.[A-Za-z_][A-Za-z0-9_-]*)*$/.test(manifest.module)) {
    fail(`invalid Toy module name '${manifest.module}'`);
  }

  if (!Array.isArray(manifest.headers) || manifest.headers.length === 0) {
    fail('headers must be a non-empty array');
  }
  const headers = new Set();
  for (const [index, header] of manifest.headers.entries()) {
    requireString(header, `headers[${index}]`);
    if (!/^[A-Za-z0-9_./+-]+$/.test(header) || header.includes('..')) {
      fail(`headers[${index}] is not a safe include path`);
    }
    if (headers.has(header)) fail(`duplicate header '${header}'`);
    headers.add(header);
  }

  if (!Array.isArray(manifest.functions) || manifest.functions.length === 0) {
    fail('functions must be a non-empty array');
  }
  const words = new Set();
  for (const [index, fn] of manifest.functions.entries()) {
    const field = `functions[${index}]`;
    if (!fn || typeof fn !== 'object' || Array.isArray(fn)) {
      fail(`${field} must be an object`);
    }
    requireKeys(fn, new Set(['name', 'word', 'returns', 'args']), field);
    requireString(fn.name, `${field}.name`);
    if (!/^[A-Za-z_][A-Za-z0-9_]*$/.test(fn.name)) {
      fail(`${field}.name is not a C identifier`);
    }
    if (fn.word !== undefined) requireString(fn.word, `${field}.word`);
    const word = fn.word || fn.name;
    if (!/^[A-Za-z_+*%<>=!?-][A-Za-z0-9_+*%<>=!?-]*$/.test(word)) {
      fail(`${field}.word is not a native Toy word name`);
    }
    if (words.has(word)) fail(`duplicate Toy word '${word}'`);
    words.add(word);

    validateType(fn.returns, `${field}.returns`, true);
    if (!Array.isArray(fn.args)) fail(`${field}.args must be an array`);
    if (fn.args.length > 32) fail(`${field}.args supports at most 32 arguments`);
    for (const [argIndex, type] of fn.args.entries()) {
      validateType(type, `${field}.args[${argIndex}]`, false);
    }
  }
  return manifest;
}

function loadManifest(manifestPath) {
  let manifest;
  try {
    manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));
  } catch (error) {
    fail(`could not read manifest '${manifestPath}': ${error.message}`);
  }
  return validateManifest(manifest);
}

function cString(value) {
  return JSON.stringify(value);
}

function cType(type, argument = false) {
  switch (type) {
    case 'void': return 'void';
    case 'bool': return 'bool';
    case 'i8': return 'int8_t';
    case 'u8': return 'uint8_t';
    case 'i16': return 'int16_t';
    case 'u16': return 'uint16_t';
    case 'i32': return 'int32_t';
    case 'u32': return 'uint32_t';
    case 'i64': return 'int64_t';
    case 'u64': return 'uint64_t';
    case 'isize': return 'intptr_t';
    case 'usize': return 'uintptr_t';
    case 'f32': return 'float';
    case 'f64': return 'double';
    case 'cstr': return argument ? 'char *' : 'const char *';
    default: fail(`internal error: unsupported type '${type}'`);
  }
}

function cDeclaration(type, name, argument = false) {
  const separator = type === 'cstr' ? '' : ' ';
  return `${cType(type, argument)}${separator}${name}`;
}

function argumentMessage(moduleName, word, index, type) {
  return cString(`${moduleName}.${word} argument ${index + 1} expected ${type}`);
}

function emitFailure(lines, condition, message) {
  lines.push(
    `    if (!(${condition})) {`,
    `        status = toy_fail(state, ${message});`,
    '        goto cleanup;',
    '    }'
  );
}

function emitArgumentDeclarations(lines, type, index) {
  const argument = `argument_${index}`;
  switch (type) {
    case 'bool':
    case 'i64':
    case 'f32':
    case 'f64':
      lines.push(`    ${cDeclaration(type, argument)} = 0;`);
      break;
    case 'cstr':
      lines.push(
        `    ${cDeclaration(type, argument, true)} = NULL;`,
        `    const char *string_data_${index} = NULL;`,
        `    size_t string_length_${index} = 0;`
      );
      break;
    default:
      lines.push(
        `    int64_t raw_argument_${index} = 0;`,
        `    ${cDeclaration(type, argument)} = 0;`
      );
      break;
  }
}

function emitArgumentConversion(lines, moduleName, word, type, index, depth) {
  const argument = `argument_${index}`;
  const raw = `raw_argument_${index}`;
  const message = argumentMessage(moduleName, word, index, type);
  switch (type) {
    case 'bool':
      emitFailure(lines, `toy_get_bool(state, ${depth}, &${argument})`, message);
      break;
    case 'i8':
      emitFailure(
        lines,
        `toy_get_int(state, ${depth}, &${raw}) && ${raw} >= INT8_MIN && ${raw} <= INT8_MAX`,
        message
      );
      lines.push(`    ${argument} = (int8_t)${raw};`);
      break;
    case 'u8':
      emitFailure(
        lines,
        `toy_get_int(state, ${depth}, &${raw}) && ${raw} >= 0 && ${raw} <= UINT8_MAX`,
        message
      );
      lines.push(`    ${argument} = (uint8_t)${raw};`);
      break;
    case 'i16':
      emitFailure(
        lines,
        `toy_get_int(state, ${depth}, &${raw}) && ${raw} >= INT16_MIN && ${raw} <= INT16_MAX`,
        message
      );
      lines.push(`    ${argument} = (int16_t)${raw};`);
      break;
    case 'u16':
      emitFailure(
        lines,
        `toy_get_int(state, ${depth}, &${raw}) && ${raw} >= 0 && ${raw} <= UINT16_MAX`,
        message
      );
      lines.push(`    ${argument} = (uint16_t)${raw};`);
      break;
    case 'i32':
      emitFailure(
        lines,
        `toy_get_int(state, ${depth}, &${raw}) && ${raw} >= INT32_MIN && ${raw} <= INT32_MAX`,
        message
      );
      lines.push(`    ${argument} = (int32_t)${raw};`);
      break;
    case 'u32':
      emitFailure(
        lines,
        `toy_get_int(state, ${depth}, &${raw}) && ${raw} >= 0 && (uint64_t)${raw} <= UINT32_MAX`,
        message
      );
      lines.push(`    ${argument} = (uint32_t)${raw};`);
      break;
    case 'i64':
      emitFailure(lines, `toy_get_int(state, ${depth}, &${argument})`, message);
      break;
    case 'u64':
      emitFailure(lines, `toy_get_int(state, ${depth}, &${raw}) && ${raw} >= 0`, message);
      lines.push(`    ${argument} = (uint64_t)${raw};`);
      break;
    case 'isize':
      emitFailure(
        lines,
        `toy_get_int(state, ${depth}, &${raw}) && ${raw} >= INTPTR_MIN && ${raw} <= INTPTR_MAX`,
        message
      );
      lines.push(`    ${argument} = (intptr_t)${raw};`);
      break;
    case 'usize':
      emitFailure(
        lines,
        `toy_get_int(state, ${depth}, &${raw}) && ${raw} >= 0 && (uint64_t)${raw} <= UINTPTR_MAX`,
        message
      );
      lines.push(`    ${argument} = (uintptr_t)${raw};`);
      break;
    case 'f32':
      emitFailure(
        lines,
        `binding_get_number(state, ${depth}, &raw_number_${index}) && ` +
          `(!isfinite(raw_number_${index}) || ` +
          `(raw_number_${index} >= -FLT_MAX && raw_number_${index} <= FLT_MAX))`,
        message
      );
      lines.push(`    ${argument} = (float)raw_number_${index};`);
      break;
    case 'f64':
      emitFailure(lines, `binding_get_number(state, ${depth}, &${argument})`, message);
      break;
    case 'cstr':
      emitFailure(
        lines,
        `toy_get_string(state, ${depth}, &string_data_${index}, &string_length_${index}) && ` +
          `(string_length_${index} == 0 || ` +
          `!memchr(string_data_${index}, '\\0', string_length_${index}))`,
        message
      );
      lines.push(
        `    ${argument} = malloc(string_length_${index} + 1);`,
        `    if (!${argument}) {`,
        `        status = toy_fail(state, ${cString(`${moduleName}.${word} could not copy argument ${index + 1}`)});`,
        '        goto cleanup;',
        '    }',
        `    memcpy(${argument}, string_data_${index}, string_length_${index});`,
        `    ${argument}[string_length_${index}] = '\\0';`
      );
      break;
    default:
      fail(`internal error: unsupported argument type '${type}'`);
  }
}

function emitReturn(lines, moduleName, word, type, call) {
  const prefix = `${moduleName}.${word}`;
  if (type === 'void') {
    lines.push(`    ${call};`, '    status = TOY_OK;');
    return;
  }

  lines.push(`    ${cDeclaration(type, 'result')} = ${call};`);
  switch (type) {
    case 'bool':
      lines.push('    status = toy_push_bool(state, result);');
      break;
    case 'i8':
    case 'u8':
    case 'i16':
    case 'u16':
    case 'i32':
    case 'u32':
    case 'i64':
    case 'isize':
      lines.push('    status = toy_push_int(state, (int64_t)result);');
      break;
    case 'u64':
    case 'usize':
      lines.push(
        '    if ((uint64_t)result > INT64_MAX) {',
        `        status = toy_fail(state, ${cString(`${prefix} returned ${type} outside Toy's range`)});`,
        '    } else {',
        '        status = toy_push_int(state, (int64_t)result);',
        '    }'
      );
      break;
    case 'f32':
    case 'f64':
      lines.push('    status = toy_push_float(state, (double)result);');
      break;
    case 'cstr':
      lines.push(
        '    if (!result) {',
        `        status = toy_fail(state, ${cString(`${prefix} returned a null cstr`)});`,
        '    } else {',
        '        status = toy_push_string(state, result, strlen(result));',
        '    }'
      );
      break;
    default:
      fail(`internal error: unsupported return type '${type}'`);
  }
}

function renderFunction(manifest, fn, index) {
  const word = fn.word || fn.name;
  const lines = [
    `static toy_status binding_word_${index}(toy_state *state) {`,
    '    toy_status status = TOY_ERROR;',
  ];

  for (const [argIndex, type] of fn.args.entries()) {
    emitArgumentDeclarations(lines, type, argIndex);
    if (type === 'f32') lines.push(`    double raw_number_${argIndex} = 0.0;`);
  }
  if (fn.args.length > 0) lines.push('');

  for (const [argIndex, type] of fn.args.entries()) {
    emitArgumentConversion(
      lines,
      manifest.module,
      word,
      type,
      argIndex,
      fn.args.length - argIndex - 1
    );
  }
  if (fn.args.length > 0) {
    lines.push(
      '    if (!toy_pop(state, ' + fn.args.length + ')) {',
      `        status = toy_fail(state, ${cString(`${manifest.module}.${word} failed to pop its inputs`)});`,
      '        goto cleanup;',
      '    }'
    );
  }

  const call = `${fn.name}(${fn.args.map((_, argIndex) => `argument_${argIndex}`).join(', ')})`;
  emitReturn(lines, manifest.module, word, fn.returns, call);
  lines.push('    goto cleanup;', '', 'cleanup:');
  for (const [argIndex, type] of fn.args.entries()) {
    if (type === 'cstr') lines.push(`    free(argument_${argIndex});`);
  }
  lines.push('    return status;', '}', '');
  return lines;
}

function renderBinding(manifest) {
  const needsNumberHelper = manifest.functions.some((fn) =>
    fn.args.some((type) => type === 'f32' || type === 'f64')
  );
  const lines = [
    `/* ${generatedComment} */`,
    '#include "toy_module.h"',
    '',
    ...manifest.headers.map((header) => `#include "${header}"`),
    '',
    '#include <float.h>',
    '#include <math.h>',
    '#include <stdint.h>',
    '#include <stdlib.h>',
    '#include <string.h>',
    '',
  ];

  if (needsNumberHelper) {
    lines.push(
      'static bool binding_get_number(toy_state *state, size_t depth,',
      '                               double *value) {',
      '    if (toy_stack_type(state, depth) == TOY_TYPE_FLOAT) {',
      '        return toy_get_float(state, depth, value);',
      '    }',
      '    int64_t integer = 0;',
      '    if (!toy_get_int(state, depth, &integer)) return false;',
      '    *value = (double)integer;',
      '    return true;',
      '}',
      ''
    );
  }

  for (const [index, fn] of manifest.functions.entries()) {
    lines.push(...renderFunction(manifest, fn, index));
  }

  lines.push('static const toy_native_word binding_words[] = {');
  for (const [index, fn] of manifest.functions.entries()) {
    lines.push(`    {${cString(fn.word || fn.name)}, binding_word_${index}},`);
  }
  lines.push(
    '};',
    '',
    'static const toy_module_export binding_module = {',
    '    TOY_MODULE_ABI_VERSION,',
    '    sizeof(toy_module_export),',
    `    ${cString(manifest.module)},`,
    '    binding_words,',
    '    sizeof(binding_words) / sizeof(binding_words[0]),',
    '};',
    '',
    'TOY_MODULE_EXPORT const toy_module_export *toy_module_v1(',
    '    const toy_module_api *api) {',
    '    if (!toy_module_bind(api)) return NULL;',
    '    return &binding_module;',
    '}',
    ''
  );
  return lines.join('\n');
}

function main() {
  const args = process.argv.slice(2);
  const check = args[0] === '--check';
  const expectedLength = check ? 3 : 2;
  if (args.length !== expectedLength) {
    console.error(
      'usage: node tools/generate-binding.js [--check] <manifest.json> <output.c>'
    );
    process.exitCode = 2;
    return;
  }

  const manifestPath = path.resolve(args[check ? 1 : 0]);
  const outputPath = path.resolve(args[check ? 2 : 1]);
  const expected = renderBinding(loadManifest(manifestPath));
  if (check) {
    const actual = fs.existsSync(outputPath)
      ? fs.readFileSync(outputPath, 'utf8')
      : null;
    if (actual !== expected) {
      console.error(`out of date: ${outputPath}`);
      process.exitCode = 1;
    } else {
      console.log(`generated binding is up to date: ${outputPath}`);
    }
    return;
  }

  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  fs.writeFileSync(outputPath, expected);
  console.log(`wrote ${outputPath}`);
}

if (require.main === module) {
  try {
    main();
  } catch (error) {
    console.error(`error: ${error.message}`);
    process.exitCode = 1;
  }
}

module.exports = { renderBinding, validateManifest };
